version: '3.8'

services:
  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "3001:80"
    environment:
      - REACT_APP_API_URL=http://backend:5000
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - FLASK_ENV=development
      - DEBUG_METRICS=1
    ports:
      - "5000:5000"
    networks:
      - app-network



networks:
  app-network:
    driver: bridge
