version: '3.8'

services:
  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "3001:80"
    environment:
      - REACT_APP_API_URL=http://backend:5000
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - FLASK_ENV=development
      - DEBUG_METRICS=1
    ports:
      - "5000:5000"
    networks:
      - app-network
    labels:
      - "monitoring=flask_app" # Etiqueta para identificar el servicio en Prometheus

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml # Archivo de configuración
    ports:
      - "9090:9090"
    networks:
      - app-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards

networks:
  app-network:
    driver: bridge

volumes:
  grafana-data:
