apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: mi-proyecto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: skardevops/backend:1.0.0
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_ENV
              value: "development"
            - name: DEBUG_METRICS
              value: "1"
