apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: mi-proyecto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: skardevops/frontend:1.0.0
          ports:
            - containerPort: 80
