apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: mi-proyecto
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'flask'
        static_configs:
          - targets: ['backend:5000']
